// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/goods.proto

package goods

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "go-micro.dev/v5/client"
	server "go-micro.dev/v5/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Goods service

type GoodsService interface {
	AddGoods(ctx context.Context, in *AddGoodsReq, opts ...client.CallOption) (*AddGoodsResp, error)
	GetGoods(ctx context.Context, in *GetGoodsReq, opts ...client.CallOption) (*GetGoodsResp, error)
}

type goodsService struct {
	c    client.Client
	name string
}

func NewGoodsService(name string, c client.Client) GoodsService {
	return &goodsService{
		c:    c,
		name: name,
	}
}

func (c *goodsService) AddGoods(ctx context.Context, in *AddGoodsReq, opts ...client.CallOption) (*AddGoodsResp, error) {
	req := c.c.NewRequest(c.name, "Goods.AddGoods", in)
	out := new(AddGoodsResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsService) GetGoods(ctx context.Context, in *GetGoodsReq, opts ...client.CallOption) (*GetGoodsResp, error) {
	req := c.c.NewRequest(c.name, "Goods.GetGoods", in)
	out := new(GetGoodsResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Goods service

type GoodsHandler interface {
	AddGoods(context.Context, *AddGoodsReq, *AddGoodsResp) error
	GetGoods(context.Context, *GetGoodsReq, *GetGoodsResp) error
}

func RegisterGoodsHandler(s server.Server, hdlr GoodsHandler, opts ...server.HandlerOption) error {
	type goods interface {
		AddGoods(ctx context.Context, in *AddGoodsReq, out *AddGoodsResp) error
		GetGoods(ctx context.Context, in *GetGoodsReq, out *GetGoodsResp) error
	}
	type Goods struct {
		goods
	}
	h := &goodsHandler{hdlr}
	return s.Handle(s.NewHandler(&Goods{h}, opts...))
}

type goodsHandler struct {
	GoodsHandler
}

func (h *goodsHandler) AddGoods(ctx context.Context, in *AddGoodsReq, out *AddGoodsResp) error {
	return h.GoodsHandler.AddGoods(ctx, in, out)
}

func (h *goodsHandler) GetGoods(ctx context.Context, in *GetGoodsReq, out *GetGoodsResp) error {
	return h.GoodsHandler.GetGoods(ctx, in, out)
}
