// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/service-micro-demo1.proto

package service

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "go-micro.dev/v5/client"
	server "go-micro.dev/v5/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Service service-micro-demo1

type Service interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Service_StreamService, error)
}

type service struct {
	c    client.Client
	name string
}

func NewService(name string, c client.Client) Service {
	return &service{
		c:    c,
		name: name,
	}
}

func (c *service) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Service.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *service) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Service_StreamService, error) {
	req := c.c.NewRequest(c.name, "Service.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &serviceStream{stream}, nil
}

type Service_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	CloseSend() error
	Close() error
	Recv() (*StreamingResponse, error)
}

type serviceStream struct {
	stream client.Stream
}

func (x *serviceStream) CloseSend() error {
	return x.stream.CloseSend()
}

func (x *serviceStream) Close() error {
	return x.stream.Close()
}

func (x *serviceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *serviceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *serviceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *serviceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Service service-micro-demo1

type ServiceHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Service_StreamStream) error
}

func RegisterServiceHandler(s server.Server, hdlr ServiceHandler, opts ...server.HandlerOption) error {
	type service interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
	}
	type Service struct {
		service
	}
	h := &serviceHandler{hdlr}
	return s.Handle(s.NewHandler(&Service{h}, opts...))
}

type serviceHandler struct {
	ServiceHandler
}

func (h *serviceHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.ServiceHandler.Call(ctx, in, out)
}

func (h *serviceHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.ServiceHandler.Stream(ctx, m, &serviceStreamStream{stream})
}

type Service_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type serviceStreamStream struct {
	stream server.Stream
}

func (x *serviceStreamStream) Close() error {
	return x.stream.Close()
}

func (x *serviceStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *serviceStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *serviceStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *serviceStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}
