// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/goods.proto

package goods

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddGoodsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddGoodsReq) Reset() {
	*x = AddGoodsReq{}
	mi := &file_proto_goods_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddGoodsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGoodsReq) ProtoMessage() {}

func (x *AddGoodsReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goods_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGoodsReq.ProtoReflect.Descriptor instead.
func (*AddGoodsReq) Descriptor() ([]byte, []int) {
	return file_proto_goods_proto_rawDescGZIP(), []int{0}
}

func (x *AddGoodsReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AddGoodsReq) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *AddGoodsReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type AddGoodsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddGoodsResp) Reset() {
	*x = AddGoodsResp{}
	mi := &file_proto_goods_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddGoodsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGoodsResp) ProtoMessage() {}

func (x *AddGoodsResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_goods_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGoodsResp.ProtoReflect.Descriptor instead.
func (*AddGoodsResp) Descriptor() ([]byte, []int) {
	return file_proto_goods_proto_rawDescGZIP(), []int{1}
}

func (x *AddGoodsResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *AddGoodsResp) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

var File_proto_goods_proto protoreflect.FileDescriptor

const file_proto_goods_proto_rawDesc = "" +
	"\n" +
	"\x11proto/goods.proto\x12\x05goods\"S\n" +
	"\vAddGoodsReq\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"4\n" +
	"\fAddGoodsResp\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code2<\n" +
	"\x05Goods\x123\n" +
	"\bAddGoods\x12\x12.goods.AddGoodsReq\x1a\x13.goods.AddGoodsRespB\x0fZ\r./proto;goodsb\x06proto3"

var (
	file_proto_goods_proto_rawDescOnce sync.Once
	file_proto_goods_proto_rawDescData []byte
)

func file_proto_goods_proto_rawDescGZIP() []byte {
	file_proto_goods_proto_rawDescOnce.Do(func() {
		file_proto_goods_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_goods_proto_rawDesc), len(file_proto_goods_proto_rawDesc)))
	})
	return file_proto_goods_proto_rawDescData
}

var file_proto_goods_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_goods_proto_goTypes = []any{
	(*AddGoodsReq)(nil),  // 0: goods.AddGoodsReq
	(*AddGoodsResp)(nil), // 1: goods.AddGoodsResp
}
var file_proto_goods_proto_depIdxs = []int32{
	0, // 0: goods.Goods.AddGoods:input_type -> goods.AddGoodsReq
	1, // 1: goods.Goods.AddGoods:output_type -> goods.AddGoodsResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_goods_proto_init() }
func file_proto_goods_proto_init() {
	if File_proto_goods_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_goods_proto_rawDesc), len(file_proto_goods_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_goods_proto_goTypes,
		DependencyIndexes: file_proto_goods_proto_depIdxs,
		MessageInfos:      file_proto_goods_proto_msgTypes,
	}.Build()
	File_proto_goods_proto = out.File
	file_proto_goods_proto_goTypes = nil
	file_proto_goods_proto_depIdxs = nil
}
